version: '3.8'

services:
  app:
    container_name: ricky-and-morty-microfrontend-container
    image: ricky-and-morty-microfrontend-container
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3005:3005
