version: '3.8'

services:
  vite_docker:
    container_name: rick-and-morty-microfrontend-container
    entrypoint: /bin/sh
    image: node:alpine
    volumes:
      - .:/app
    tty: true
    ports:
      - 3005:3005
    working_dir: /app
